### ISSUE TITLE
Remove config/*.json files from the repo

### ISSUE THREAD

**Issue by jonuy** [DoSomething/ds-mdata-responder#397]
After #394, it should be safe to remove these files from the repo.

`pull_config.sh` might need to be modified to use mongoexport + mongoimport instead of mongodump + mongorestore so that we have local .json files to work with in case we need to work with those .json files locally? Maybe?

**Comment by tongxiang** [comment]
Hmmm...your point about mongoexport and mongimport sounds reasonable. 

The Compose.io GUI still is pretty good, though--if it comes down to it, we can still manually-hand edit config online. 

My question: are there any risks to doing this before we have a working CMS?

**Comment by jonuy** [comment]
Since all the configs are already up on production and that we've got backups of it, I feel ok about removing the config files even before we have a working CMS. And like you said, the compose.io gui is good enough to get the job done for now.
