### ISSUE TITLE
Add caption question to report back flow

### ISSUE THREAD

**Issue by jonuy** [DoSomething/ds-mdata-responder#406]
This could be done in one of two ways.

1. Replace/combine the "why" question with the caption question. This will only require us to modify the data that's sent to the Content API.
2. Add an extra question to ask for a caption for the photo. This will need both a modification to data sent to the Content API and support for an additional step in the report back flow.

Waiting on what data suggests we do. Should hear back by EOD 2/25.

cc: @mikefantini

**Comment by mikefantini** [comment]
@jonuy based on the data (very low dropoff once a user submits a photo) we're going to add the extra caption and monitor to see if dropoff increases.

**Comment by jonuy** [comment]
Question for caption will be asked after receiving the photo, followed by quantity then why questions.
