### ISSUE TITLE
Add .env to .gitignore

### ISSUE THREAD

**Issue by aaronschachter** [DoSomething/ds-mdata-responder#522]
Seems like we could get away with setting variables locally with a `.env` file instead of the `.bash_profile`, like the [https://github.com/DoSomething/ds-mdata-responder/wiki/Setup](wiki) suggests.

* [ ] Update `.gitignore`
* [ ] Update README to document that `.env` may be used (and is preferred?) over `.bash_profile`

cc @deadlybutter

**Comment by deadlybutter** [comment]
yeah locally i added .env to the git ignore but i never pushed it up

**Comment by aaronschachter** [comment]
I thought I got this working but it doesn't seem to read the `.env` file, when I try to run `node server.js` I got a 401 on the ds-content-api `userLogin`: 'Missing required argument username' 

Possibly a dumb question but @deadlybutter to get this working do we need to add the [dotenv](https://www.npmjs.com/package/dotenv) package?

**Comment by deadlybutter** [comment]
easier way, `heroku local` I think it is. Requires the heroku toolbekt which you need anyway fo view logs / manage the app in production
