### ISSUE TITLE
Create valid email for user creation

### ISSUE THREAD

**Issue by mshmsh5000** [DoSomething/ds-mdata-responder#557]
_BUG_
-------------------
#### Current Behavior
- When creating a new user in Phoenix without a known email address, `ds-mdata-responder` creates an email address out of the user's SMS number plus `@mobile`. In May 2016, the Phoenix endpoint [added (very reasonable) email validation](https://github.com/DoSomething/phoenix/commit/6b7dbda931ac03d31d51571c0f961de9552c7fb7#diff-e8eea0df8599af7b106dde62fad4bff0R155), and started rejecting these.

#### Desired Behavior
- We need to decide on a new default email pattern that validates. Suggestion: `[SMS]@mobile.import` 

#### Steps to Replicate
- Use the logic in [this `createUserThenReportBack` method](https://github.com/DoSomething/ds-mdata-responder/blob/c7da5b0358da2a1ac63aca13a38a706220e1c376/app/lib/reportback/index.js#L352) to create a default `[NUMBER]@mobile` address and submit as part of a POST to Phoenix's `/api/v1/users` endpoint.
- Rejection & sadness

#### Why This Matters
All MoCo-originated user creation should be failing because of this. To view in Kibana, search `422 AND POST`.

#### Relevant Screenshots + Links
- Kibana: https://cl.ly/0n3o2q3o3d0l
- `ds-mdata-responder` logs: https://cl.ly/3i0S081S3X2e

**Comment by aaronschachter** [comment]
Deployed 1.1.0 to production today and confirmed this is resolved:
> 2016-08-08T19:07:04.126048+00:00 app[web.2]: [32minfo[39m: phoenix.userCreate success uid: 4001183

Verified email was created with `@mobile.import`.
